version: '3.8'

services:
  cv-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-to-pdf-api
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8080
      - API_KEY=${API_KEY:-your-secret-api-key-change-this}
      - TEMPLATE_NAME=${TEMPLATE_NAME:-option-b.hbs}
      - TEMPLATE_DIR=templates
      - PUPPETEER_TIMEOUT=${PUPPETEER_TIMEOUT:-30000}
      - PDF_RETRY_ATTEMPTS=${PDF_RETRY_ATTEMPTS:-1}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-2mb}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cv-api-network
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  cv-api-network:
    driver: bridge

